<a href="https://colab.research.google.com/github/iamsanviv/proyects/blob/main/Copia_de_numpy_challenge.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#NumPy Challenge

Create a NumPy ndarray object by using this list of numbers [7,8,4,5,1,2].


In [ ]:
import numpy as np
arr1 = np.array([7, 8, 4, 5, 1, 2])
print(arr1)

[7 8 4 5 1 2]


Using slicing print the elements from index 3 to the end of the array.



In [ ]:
print(arr1[3:])

[5 1 2]


Using slicing print all the elements except the last one.



In [ ]:
print(arr1[:-1])

[7 8 4 5 1]


Using slicing print the elements from index 1 to index 4 of the array.



In [ ]:
print(arr1[1:5])

[8 4 5 1]


Reshape the array into a 3 rows and 2 cols (3,2).



In [ ]:
print(arr1.reshape(3, 2))

[[7 8]
 [4 5]
 [1 2]]


Print all the array elements one by one (iterating).



In [ ]:
for num in arr1:
  print(num)

7
8
4
5
1
2


Create a new NumPy ndarray object by using this list of numbers [0,6,9].



In [ ]:
arr2 = np.array([0, 6, 9])
print(arr2)

[0 6 9]


Join the two arrays.



In [ ]:
arr = np.concatenate((arr1, arr2))
print(arr)

[7 8 4 5 1 2 0 6 9]


Using filtering print only the odd numbers of the joined array.



In [ ]:
print(np.extract(arr % 2 != 0, arr))

[7 5 1 9]


Sort the joined array elements.



In [ ]:
print(np.sort(arr))

[0 1 2 4 5 6 7 8 9]


Store in an array the names of the months.



In [ ]:
meses = np.array(['Enero', 'Febrero', 'Marzo', 'Abril', 'Mayo', 'Junio',
                         'Julio', 'Agosto', 'Septiembre', 'Octubre', 'Noviembre', 'Diciembre'])

print(meses)

['Enero' 'Febrero' 'Marzo' 'Abril' 'Mayo' 'Junio' 'Julio' 'Agosto'
 'Septiembre' 'Octubre' 'Noviembre' 'Diciembre']


Split the months array in 4 periods of 3 elements each one.



In [ ]:
split = np.split(meses, 4)

for periods in split:
    print(periods)

['Enero' 'Febrero' 'Marzo']
['Abril' 'Mayo' 'Junio']
['Julio' 'Agosto' 'Septiembre']
['Octubre' 'Noviembre' 'Diciembre']


Create an array with genre information ['F','M','F','F','M','F'].



In [ ]:
gender = np.array(['F', 'M', 'F', 'F', 'M', 'F'])

print(gender)

['F' 'M' 'F' 'F' 'M' 'F']


Find the indexes where the value is F.



In [ ]:
print(np.where(gender == 'F')[0])

[0 2 3 5]


Store in an array the age information [18,20,19,23,19,20].



In [ ]:
age = np.array([18, 20, 19, 23, 19, 20])

print(age)

[18 20 19 23 19 20]


Create a filter array with values < 20.



In [ ]:
filter_age = age < 20
print(age[filter_age])

[18 19 19]


Change the 3 index element with a value of 22



In [ ]:
age[3] = 22
print(age)

[18 20 19 22 19 20]


Print the 4 index element.

In [ ]:
print(age[4])

19
